export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const SET_LOGGED_OUT_USER = "SET_LOGGED_OUT_USER";

export const REFRESH_STATE = "REFRESH_STATE";

export const SET_IS_SIGNUP = "SET_IS_SIGNUP";
export const RESET_IS_SIGNUP = "RESET_IS_SIGNUP";

export const SET_IS_SUBMITING = "SET_IS_SUBMITING";
export const RESET_IS_SUBMITING = "RESET_IS_SUBMITING";
