// types.js
export const FETCH_CATEGORY_LIST_REQUEST = "FETCH_CATEGORY_LIST_REQUEST";
export const FETCH_USER_CATEGORY_LIST_SUCCESS = "FETCH_USER_CATEGORY_LIST_SUCCESS";
export const FETCH_USER_CATEGORY_LIST_FAILURE = "FETCH_USER_CATEGORY_LIST_FAILURE";

export const FETCH_SUBCATEGORY_LIST_REQUEST = "FETCH_SUBCATEGORY_LIST_REQUEST";
export const FETCH_SUBCATEGORY_LIST_SUCCESS = "FETCH_SUBCATEGORY_LIST_SUCCESS";
export const FETCH_SUBCATEGORY_LIST_FAILURE = "FETCH_SUBCATEGORY_LIST_FAILURE";
