export const FETCH_QUESTION_LIST_REQUEST = "FETCH_QUESTION_LIST_REQUEST";
export const FETCH_QUESTION_LIST_SUCCESS = "FETCH_QUESTION_LIST_SUCCESS";
export const FETCH_QUESTION_LIST_FAILURE = "FETCH_QUESTION_LIST_FAILURE";

export const FETCH_QUESTION_LIST_BY_ID_REQUEST = "FETCH_QUESTION_LIST_BY_ID_REQUEST";
export const FETCH_QUESTION_LIST_BY_ID_SUCCESS = "FETCH_QUESTION_LIST_BY_ID_SUCCESS";
export const FETCH_QUESTION_LIST_BY_ID_FAILURE = "FETCH_QUESTION_LIST_BY_ID_FAILURE";

export const FETCH_ANSWER_LIST_REQUEST = "FETCH_ANSWER_LIST_REQUEST";
export const FETCH_ANSWER_LIST_SUCCESS = "FETCH_ANSWER_LIST_SUCCESS";
export const FETCH_ANSWER_LIST_FAILURE = "FETCH_ANSWER_LIST_FAILURE";

export const FETCH_SUGGESTION_REQUEST = "FETCH_SUGGESTION_LIST_REQUEST";
export const FETCH_SUGGESTION_SUCCESS = "FETCH_SUGGESTION_LIST_SUCCESS";
export const FETCH_SUGGESTION_FAILURE = "FETCH_SUGGESTION_LIST_FAILURE";
