export const FETCH_QUESTION_LIST_REQUEST = "FETCH_QUESTION_LIST_REQUEST";
export const FETCH_QUESTION_LIST_SUCCESS = "FETCH_QUESTION_LIST_SUCCESS";
export const FETCH_QUESTION_LIST_FAILURE = "FETCH_QUESTION_LIST_FAILURE";

export const FETCH_ANSWER_LIST_REQUEST = "FETCH_ANSWER_LIST_REQUEST";
export const FETCH_ANSWER_LIST_SUCCESS = "FETCH_ANSWER_LIST_SUCCESS";
export const FETCH_ANSWER_LIST_FAILURE = "FETCH_ANSWER_LIST_FAILURE";
