export const FETCH_SUB_CATEGORY_LIST_REQUEST = "FETCH_SUB_CATEGORY_LIST_REQUEST";
export const FETCH_SUB_CATEGORY_LIST_SUCCESS = "FETCH_SUB_CATEGORY_LIST_SUCCESS";
export const FETCH_SUB_CATEGORY_LIST_FAILURE = "FETCH_SUB_CATEGORY_LIST_FAILURE";

export const RESET_SUB_CATEGORY_LIST_DATA = "RESET_SUB_CATEGORY_LIST_DATA";

export const FETCH_SUB_CATEGORY_BY_ID_REQUEST = "FETCH_SUB_CATEGORY_BY_ID_REQUEST";
export const FETCH_SUB_CATEGORY_BY_ID_SUCCESS = "FETCH_SUB_CATEGORY_BY_ID_SUCCESS";
export const FETCH_SUB_CATEGORY_BY_ID_FAILURE = "FETCH_SUB_CATEGORY_BY_ID_FAILURE";
